### ISSUE TITLE
JS_SCRIPT_TYPE is not deflined with latest Chrome version

### ISSUE THREAD

**Issue by slybridges** [krohling/scriptly#1]
Hi,

First of all, thanks for Scriptly! It's been working great so far.

After updating to the latest Chrome version (56.0.2924.76) today, Scriptly stopped working when used directly (with no transpiling of code).

I'm getting the following error:
```
Uncaught (in promise) ReferenceError: JS_SCRIPT_TYPE is not defined
    at Object.loadJavascript (eval at 354 (0.4b5a31e….hot-update.js:6), <anonymous>:33:47)
    at MySampleApp (eval at <anonymous> (app.js:5460), <anonymous>:90:72) 
    at .....
```

I'm not sure what changed in Chrome but if I replace all `const` declarations in `index.js` with var, it solves it.

**Comment by krohling** [comment]
Hi slybridges, thanks for the heads up, working on a fix now...

**Comment by krohling** [comment]
Ok, 0.0.7 is live on npm with this fix.  Thanks again for letting me know!

**Comment by slybridges** [comment]
hi @krohling, awesome thanks!
I confirm latest version fixes the problem.
